<?header("Content-Type: text/xml; charset=UTF8")?>
<?$filter = new filter()?>
<?='<xml version="1.0" encoding="UTF-8"?>'?>
<rss version="2.0">
<channel>
<title><?=$main['title']?></title>
<link><?=$main['link']?></link>
<description><?=$main['description']?></description>
<language>ru</language>
<?if (isset($items)):?>
<?foreach ($items as $item):?>
	<item>
		<title><?=$filter->source($item['title'])->html2text()->entity('xml')?></title>
		<description><?=$filter->source($item['description'])->html2text()->entity('xml')?></description>
		<link><?=$item['url']?></link>
		<?if (isset($item['category']) and $item['category'] !== ''):?>
			<category><?=$item['category']?></category>
		<?endif?>
		<?if ($item['image']):?>
   			 <enclosure url="<?=$item['image']['url']?>" type="image/jpeg"/>
   		<?endif?>
   		<pubDate><?=_U2RFC822_modifier($item['pubDate'])?></pubDate> 	 
		<content:encoded><![CDATA[
    				<h1><?=$filter->source($item['title'])->html2text()->entity('xml')?></h1>
    				<?if (isset($item['image'])):?>
						<figure>
							<img src="<?=$item['image']['url']?>"/>
							<?if (isset($item['image']['alt'])):?>
								<figcaption>
									<?=$filter->source($item['image']['alt'])->html2text()->entity('xml')?>
								</figcaption>
							<?endif?>		
						</figure>		
					<?endif?>	
    				<?=htmllite($item['text'])?>
    				]]></content:encoded> 
		<?if ($item['author']):?>
			<author><?=$filter->source($item['author'])->html2text()->entity('xml')?></author>
		<?endif?>
	</item>
<?endforeach?>
 <?endif?>	
</channel>
</rss>