<?header("Content-Type: text/xml; charset=UTF8")?>
<?$filter = new filter()?>
<?='<?xml version="1.0" encoding="UTF-8"?>'?>
<rss version="2.0">
<channel>
<title><?=$this->c['ch_items']['title']?></title>
<link><?=SITE?></link>
<image><?=$this->c['ch_items']['image']['url']?></image>>
<description><?=$this->c['ch_items']['description']?></description>
<?foreach ($this->c['items'] as $item):?>
	<item>
		<title><?=$filter->source($item['title'])->html2text()->entity('xml')?></title>
		<description><?=$filter->source($item['fulltext'])->html2text()->entity('xml')?></description>
		<link><?=$item['link']?></link>
		<?if ($item['author']):?>
			<author><?=$filter->source($item['author'])->html2text()->entity('xml')?></author>
		<?endif?>
		<category><?=$item['category']?></category>
		<?=$item['img']?>
		<?if ($item['image_url']):?>
   			 <enclosure url="<?=$item['image_url']?>" type="image/jpeg"/>
   		<?endif?>	
	</item>
<?endforeach?>	
</channel>
</rss>