<?header("Content-Type: text/xml; charset=UTF8")?>
<?='<?xml version="1.0" encoding="UTF-8" ?>'?>
<?$filter = new filter()?>
<rss version="2.0" xmlns:mailru="http://news.mail.ru/">
  <channel>
    <?if (isset($main)):?>
    	<title><?=$main['title']?></title>
    	<link><?=$main['link']?></link>
    	<?if (isset($main['description'])):?>
    		<description><?=$main['description']?></description>
    	<?endif?>	
    	<language>ru</language>
    	<pubDate><?=_U2RFC822_modifier($items[0]['pubDate'])?></pubDate>
    	<lastBuildDate><?=_U2RFC822_modifier($items[0]['pubDate'])?></lastBuildDate>
    	<managingEditor><?=$main['email']?></managingEditor>
    	<webMaster><?=$main['email']?></webMaster>
    <?endif?>
    <?foreach ($items as $item):?>
		<item>
			<?if (isset($item['link']) and $item['link'] !== ''):?>
				<guid><?=$item['link']?></guid>
			<?endif?>
			<?if (isset($item['category']) and $item['category'] !== ''):?>
				<category><?=$item['category']?></category>
			<?endif?>
			<title><![CDATA[<?=$filter->source($item['title'])->html2text()?>]]></title>
			<description><![CDATA[<?=$filter->source($item['description'])->html2text()?>]]></description>
			<mailru:full-text><![CDATA[<?=$filter->source($item['text'])->html2text()->text2p()?>]]></mailru:full-text>
			<pubDate><?=_U2RFC822_modifier($item['pubDate'])?></pubDate>
			<?if (isset($item['link']) and $item['link'] !== ''):?>
				<link><?=$item['link']?></link>
			<?endif?>
		</item>
	<?endforeach?>	
</channel>
</rss>