<?header("Content-Type: text/xml; charset=UTF8")?>
<?$filter = new filter()?>
<?='<?xml version="1.0" encoding="UTF-8" ?>'?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
		<channel>
			<?if (isset($main)) :?>
				<title><?=$main['title']?></title>
                <link><?=$main['link']?></link>
                <language>ru</language>
				<?if (isset($main['description'])):?>
					<description><?=$main['description']?></description>
				<?endif?>	
			<?endif?>

            <?if (isset($items)):?>
				<?foreach ($items as $item):?>
					<item>
						<title><?=$filter->source($item['title'])->html2text()->entity('xml')?></title>
                        <link><?=$item['url']?></link>
                        <?if (isset($item['image'])):?>
                            <enclosure url="<?=$item['image']['url']?>" type="image/jpeg"/>
                        <?endif?>
                        <pubDate><?=_U2RFC822_modifier($item['pubDate'])?></pubDate>
                        <description><?=$filter->source($item['description'])->html2text()->entity('xml')?></description>
					</item>	
				<?endforeach?>	
			<?endif?>
        </channel>
	</rss>	
